# Numpy Assigmint

In [1]:
import numpy as np

#### 1. Write a NumPy program to test whether none of the elements of a given array is zero.


In [53]:
a=[1,2,3,5,6,7]
print(np.array(a))
print(np.all(a)) # test if ther is not zero in the array

[1 2 3 5 6 7]
True


In [54]:
def if_zero(a):
    for i in range(len(a)):
        if a[i]==0:     #if ther is zero return True
            return True
        # else :
        #     pass
    return False

if_zero(a)

False

#### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [60]:
a=np.array([0,0,0,0,0])
print(np.any(a)) # test if any numer in array is not zero

False


In [64]:
def if_numper(a):
    for i in range(len(a)):
        if a[i]==0:
            pass
        else: 
            return True
    return False
if_numper(a)

False

#### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 


In [68]:
x=np.array([1,2,3,4,5,6,7,9,0])
y=np.array([1,2,3,4,5,6,7,8,9])
np.equal(x, y) # must be the same shabe

array([ True,  True,  True,  True,  True,  True,  True, False, False])

In [74]:
def if_EW (a,a1):
    for i in range(len(a)):
        if a[i]==a1[i]:
            print (True,end=',')
        else :
            print (False,end=',')
if_EW(x,y)

True,True,True,True,True,True,True,False,False,

#### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [89]:
a=np.zeros(10,dtype='int'),np.ones(10,dtype='int'),np.ones(10,dtype='int')*5
a

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

#### 5. Write a NumPy program to create an array of the integers from 30 to70.


In [91]:
a=np.arange(30,71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

#### 6. Write a NumPy program to create a 3x3 identity matrix 

In [94]:
a=np.eye(3, dtype='int')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 7. Write a NumPy program to generate a random number between 0 and 1 

In [191]:
a=np.random.normal(0,1)
b=np.random.rand()
print(a)
b

-0.4974871475805864


array([0.30863129, 0.93248075, 0.1019096 , 0.88992829, 0.87677945,
       0.74088217, 0.76238872, 0.08141725])

#### 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 


In [175]:
a=np.random.rand(1,15)
a

array([[0.31736165, 0.43539406, 0.32265396, 0.27526385, 0.99487487,
        0.81889343, 0.16237092, 0.78353315, 0.36074393, 0.45237458,
        0.5271006 , 0.37015712, 0.17640624, 0.53019481, 0.08143174]])

#### 9.Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [118]:
a= np.arange(15,55)
a[1:]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

#### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 


In [176]:
a= np.random.randint(0, 11, 5)
a

array([7, 1, 6, 7, 2])

#### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [135]:
a=np.ones([10,10],dtype='int')
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4,5.

In [163]:
# with two defrint wayes
a=np.eye(5,k=0,dtype='int')*[1,2,3,4,5]
print(a)
#-----------------------------------------------------------------
x = np.diag([1,2,3,4,5]) 
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [166]:
a= np.zeros([4,4],'int')
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


#### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [199]:
import os
x = np.arange(10)
y = np.arange(11, 20)
np.savez('array.npz', x=x, y=y)
# Load arrays from the 'temp_arra.npz' 
with np.load('array.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


#### 15. Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select 

In [193]:
a=np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


#### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [194]:
nums = np.array([[5, 3, 7],
              [3, 4, 6],
              [1, 2, 9]])
n = 5
print(nums[nums > n])
n = 6
print(nums[nums < n])

[7 6 9]
[5 3 3 4 1 2]


# Omar Khalid Mahmmoud {AI_30}